### ISSUE TITLE
Chinese mechanical keyboards not being initialized

### ISSUE THREAD

**Issue by MalvareRJ** [No0ne/ps2x2pico#12]
Thank you so much for your work on this! This is a life saver!

I have tried two chinese mechanical keyboards (Machenike K500 and Redragon Dark Avenger K568WP) and they are not initialized. BIOS complains about missing keyboard.
However, if I turn the computer on (and consequently the adapter as well) using another USB keyboard (have used Dells and HPs without any glitches) and then switch back to any of the two chinese keyboards, they work perfectly, until I switch the computer off and on again. Resets wouldn't affect this at all.
Interestingly, I can also make these keyboards work if I initialize the computer using a USB mouse, then switch it with any of the chinese keyboards.
Seems like there's something missing in these keyboards at initialization time.

Thanks in advance for any support in this matter!

**Comment by No0ne** [comment]
Please retry with this version: https://github.com/No0ne/ps2x2pico/raw/main/ps2x2pico.uf2
It is compiled with the newest pico sdk and tinyusb release.

**Comment by No0ne** [comment]
Cool, thanks! The mouse support isn't finished yet anyway.
