### ISSUE TITLE
Multiple keys press on gaming keyboard to ps2 keyboard

### ISSUE THREAD

**Issue by darumo** [No0ne/ps2x2pico#14]
The project has been super interesting to me, yesterday I was entertained putting it together. And now I'm testing it to use it in some FPGA products that have a PS/2 port.

The drawback that I have noticed is that I cannot press depending on which keys simultaneously (arrow keys diagonally + spacebar) even when the USB keyboard can do it (gaming keyboard with support for 5 simultaneous keys)

That would be useful for example in cases like cores of MSX computers in FPGA ZXuno or SX1mini

**Comment by No0ne** [comment]
Please retry with this version: https://github.com/No0ne/ps2x2pico/raw/main/ps2x2pico.uf2
It is compiled with the newest pico sdk and tinyusb release.

I will soon make a new release which includes this.

**Comment by darumo** [comment]
I think it is the same version that I had tried, the one that is compiled together with the rest of the source code files and that says that it is about a week old.

I have not used the November version.

But I'm going to take a look and on some other device. Thank you.

**Comment by darumo** [comment]
Well, in the end you can confirm that it is working perfectly, the problem is finding a gaming keyboard that is even better so that it has those specific key combinations working.

I was very sure that this was the case and I was on the PC with a Gigabyte gaming keyboard, but in the end it turns out that it does have problems with the arrow + space keys, and that with a Logitech G512 it works perfectly.

Your adapter is going to be wonderful for the FPGAs I mentioned earlier. It would be good if you comment on this supported and confirmed feature in your project, which will be very useful to many people.

Thank you very much for this project.

**Comment by No0ne** [comment]
Thanks for debugging! All USB devices currently run with boot protocol on the pico. That means six simultaneous keypresses and all eight modifier keys are converted to PS/2, see: https://youtu.be/wdgULBpRoXk?t=1545
