### ISSUE TITLE
Freezing on KVM

### ISSUE THREAD

**Issue by yarodin** [No0ne/ps2x2pico#17]
I have KVM with 4 computers attached, ps2pico plugged to PC4 KVM USB port. 
ps/2 ports on ZX Evolution <-> ps2pico <-> PC4 USB port on KVM / Common USB port <->  USB  Logitech unifying receiver -> Logitech Mouse & Keyboard

If I switching on ZX Evolution with KVM setted to PC4 - all works perfectly untlil I have switched to PC1/2/3 computer - after several second ps2pico stop acting. Same problem if I switching on ZX Evo with KVM setted to PC1/2/3.

**Comment by No0ne** [comment]
Which hardware do you use? ps2pico or ps2x2pico?
Which firmware version did you download?

**Comment by yarodin** [comment]
ps2x2pico
beta-0.5

**Comment by No0ne** [comment]
please try out the new pre-releas beta-0.7
(remember to swap each data/clock pin pair on the 5V side)

**Comment by yarodin** [comment]
I updated firmware to beta-0.7.

"If I switching on ZX Evolution with KVM setted to PC4 - all works perfectly untlil I have switched to PC1/2/3 computer - after several second ps2pico stop acting" - this case fixed, thanks a lot.

"Same problem if I switching on ZX Evo with KVM setted to PC1/2/3." - this is not fixed.

**Comment by No0ne** [comment]
Did you connect mouse and keyboard to the KVM or keyboard only?

**Comment by yarodin** [comment]
I have one USB Logitech unifying receiver plugged to KVM and mouse and keyboard connected through it.

**Comment by No0ne** [comment]
Ok, and both stop working? or only the mouse?

**Comment by yarodin** [comment]
if I switching on ZX Evo with KVM setted to PC1/2/3 and then setting KVM to PC4 mouse and keyboard not working on PC4, but still normaly working on PC1/2/3.

Seems, ps2x2pico isn't working if mouse and keyboard is not plugged to USB (or switched off by KVM) when it power on.

**Comment by No0ne** [comment]
Ah yes, if theres nothing connected to usb it reports an error on the ps/2 side! I think i could add a jumper setting to disable that an always report OK on ps/2.

**Comment by No0ne** [comment]
[ps2x2pico.zip](https://github.com/No0ne/ps2x2pico/files/12641676/ps2x2pico.zip)
Please retry with this binary, its currently hardcoded to always answer OK.

**Comment by yarodin** [comment]
This version is working in all cases with KVM. You can close issue. Thanks.

**Comment by No0ne** [comment]
Thank you for the feedback!
