### ISSUE TITLE
Keyboard not reconnecting after power cycle

### ISSUE THREAD

**Issue by peek82** [No0ne/ps2x2pico#21]
I'm using a ps2x2pico w/ a Picomite (keyboard only) and have wired up two versions, one using the level shifter board as prescribed, and one using direct wiring from pico to pico with 4k7 'pullups' going to GP13 of the ps2x2pico. Both versions work well until a power cycle, after which I need to reset the ps2x2pico by grounding the run pin before it will reconnect to the keyboard again. As a workaround, I am toggling the run pin on boot with an extra GPIO on the picomite. Love being able to use a USB keyboard for input, much thanks!

![USB_keeb4pico_v3](https://github.com/No0ne/ps2x2pico/assets/6243304/62bc498a-c6fa-49b1-97f8-bb44344a25f6)

**Comment by No0ne** [comment]
I'm currently doing another project for the picomite: https://github.com/No0ne/hid2cdc
It is hooked up like this: https://www.thebackshed.com/forum/ViewTopic.php?TID=16545&P=1
But its not finished yet, F-keys are not working.

For debugging the powercycle bug, an you hook up a serial console to GPIO 0 and post the output?
It is sending at 115200n8

**Comment by peek82** [comment]
Thank you for the reply but when I moved from the breadboard to soldered connections the problem went away, so I'm chalking it up to a buggered up breadboard / jumper wires. It's functioning perfectly now, I really appreciate your work on this & the hid2cdc project. My current use case requires the ps2 version but I'll definitely be looking at using hid2cdc in the future.

**Comment by No0ne** [comment]
Cool, thanks!
