### ISSUE TITLE
Q. Should I connect both keyboard and mouse?

### ISSUE THREAD

**Issue by zmotme** [No0ne/ps2x2pico#4]
I am very interested on your project. But I have little knowledge about electric and embedded.

I know you already informed keyboard only project, but I found it is easier to get 4ch logic level shifter, I soledered rp2040 clone - may be yd-rp2040, and not wired mouse.

It did not worked. So I’ve ordered original rp2040 board and trying to make one.

When I connect rp2040 to ps/2, board led turns on even though PC was turned off.

I have no idea about it.

Should I connect both keyboard and mouse connect?

Or my PC send power when turned off makes problem?

I hope original rp2040 and keyboard mouse connection can solve this!

**Comment by No0ne** [comment]
Hi! Yes it is perfectly ok if you just connect the ps/2 keyboard port. It also should work with any other rp2040 board as long as the GPIO numbers match up. If not, you'll need to edit the pin definitions at the beginning of the source file and compile the software your self. Also check that the clock and data lines are connected correctly, they can not be swapped.

```
#define KBCLK 11
#define KBDAT 12
#define LVPWR 13
#define MSCLK 14
#define MSDAT 15
```

Currently I'm switching the software over to send ps/2 fames via the rp2040 PIOs on the pio-testing branch which also should make the mouse part more stable which it isn't at the moment (keyboard should be fine).

Regarding power when the PC is off: yes, this is a feature of most motherboards!
There should be a jumper on the motherboard which enables/disables PS/2 power when the PC is off.
And in the BIOS you can configure how to turn on the PC via e.g. space bar, enter or a dedicated power button on the keyboard if it has one. This should also work with ps2x2pico, but I haven't testet that yet.
