### ISSUE TITLE
Please explain what the purple wire from GPIO 40/VBUS is connecting to

### ISSUE THREAD

**Issue by megatog615** [No0ne/ps2x2pico#41]
In your photos, you have a purple wire coming from GPIO 40/VBUS and going underneath the level shifter. Where does it solder to?

**Comment by No0ne** [comment]
Its connected to PS/2 5V and HV of the level shifter so that the Pico and devcies connected to the micro USB port gets powered via the PS/2 ports.

**Comment by No0ne** [comment]
Please note that some older motherboards have non-resettable fuses rated under 300mA.
Check the power consumtion of your keyboard/mouse/hub first before plugging in!
