### ISSUE TITLE
5V PS/2 side connection with separate keyboard and mouse port; is this correct?

### ISSUE THREAD

**Issue by nistvan86** [No0ne/ps2x2pico#51]
I haven't found the schematics which shows how two PS/2 mini DIN jacks are wired when both the keyboard and mouse is being emulated. But I assume the 5V line powering the Pico (and the level shifter) should be only connected to one of the plugs in this case.
However the GND must be connected with both PS/2 jacks.

Is this correct?

**Comment by No0ne** [comment]
Correct! I also connected both 5V lines together since they are connected on the motherboard anyway.
But you should not connect them together if keyboard and mouse are not connected to the same PC!

**Comment by nistvan86** [comment]
Thanks!
Yeah, probably on the same machine it's fine to connect them together. But generally this is not a good idea.
