### ISSUE TITLE
Powering via dedicated usb connection to pc?

### ISSUE THREAD

**Issue by NoAffinity** [No0ne/ps2x2pico#54]
If additional power is needed, is it possible to wire up the 5v and ground pins of a usb A male connector to the pico and pull power from a rear panel usb input on the host pc?  With or without 5v and ground connections connected at the ps2 male connectors?

Examples:
5v and ground from a pc usb input powers the pico in addition to 5v and ground from ps/2 inputs

5v and ground from a pc usb input powers the pico with no 5v connection from the ps/2 inputs (assuming it's good practice and/or necessary to connect the ps/2 grounds)

**Comment by No0ne** [comment]
If the extra 5V are coming from the same PC it should not matter if you also connect the PS/2 5V supply.

But if you use an external supply you should not connect the PS/2 5V as it backfeeds the PC when its turned off.
The grounds should always be connected as voltages can get weird if no ground reference is given.
