### ISSUE TITLE
Corsair K60 Pro keyboard not working.

### ISSUE THREAD

**Issue by Tambotine** [No0ne/ps2x2pico#64]
I have two other keyboards both working fine, however the K60 Pro is not working.  I will check and see how to get the serial output and update here. Thank you.

**Comment by No0ne** [comment]
Which version did you test? I just made a 2.0 pre-release.

**Comment by Tambotine** [comment]
Apologies should have mentioned - I tested the 1.2 version (the latest release). Is it possible to get the 2.0 to check if keyboard works on that?

**Comment by No0ne** [comment]
Yes, downloads are here: https://github.com/No0ne/ps2x2pico/releases

**Comment by Tambotine** [comment]
Its working!! I am typing on  that keyboard now! Perfect and thank you!

**Comment by No0ne** [comment]
Cool! I've added NKRO support in this release, I think this did the trick.
