### ISSUE TITLE
Gamepad and joystick support

### ISSUE THREAD

**Issue by Sky-Jumper** [No0ne/ps2x2pico#8]
Hi!
How difficult will it be to implement gamepad support?
For example, use the gamepad buttons to emulate pressing the keyboard buttons, and move the mouse by tilting the sticks?

**Comment by ArnoldUK** [comment]
Should pretty trivial considering the source code is all there for you to modify.

**Comment by No0ne** [comment]
The [fork by anteo](/anteo/ps2pico4zx) does support gamepads.
