### ISSUE TITLE
Add Buffer option

### ISSUE THREAD

**Issue by AbhishekAKA47** [No0ne/ps2x2pico#9]
I need it to delay the mouse movement by some time. 
can you edit it, so it just buffers the mouse movement received by 1 second.
just buffer all of it, doesn't have to modify it in any way just buffer the mouse data.
(at least just give me instructions on how to do this to your code I have it opened up on visual studio code.)
and specify at which line it is (delay amount) that so its editable later on by someone not smart?

also how well does the mouse work like the polling rate and dpi for the mouse. and is the mouse jittery and stuff?
also, can I use a usba cable to connect to the bidirectional level shifter with the pc, because the cables are the same color for usb and ps2? i will close the issue if you tell me to.

**Comment by No0ne** [comment]
The mouse support is still not really finished. I'll have to calculate how much ram buffering one second of mouse frames would take. I also don't know how the polling rate would affect this. I will try a test implementation!
The last question about the usb-a cable I didn't understand, please rephrase.

**Comment by No0ne** [comment]
Didn't hear anything back from you.
